stages:
  feature_extraction:
    cmd: python src/data_processing.py
    deps:
      - src/data_processing.py
    outs:
      - data/Reviews_featurized.csv

  train:
    cmd: python src/train.py data/Reviews_featurized.csv
    deps:
      - src/train.py
      - data/Reviews_featurized.csv
    outs:
      - models/model.cbm