name: Deploy and Test Model Container

on:
  workflow_call:
  workflow_dispatch: 

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Pull Docker image from DockerHub
      run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/review_clf:latest

    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 --name review_api ${{ secrets.DOCKERHUB_USERNAME }}/review_clf:latest

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Wait and test inference endpoint
      run: |
        echo "Waiting for the API to become ready..."
        for i in {1..10}; do
          sleep 10
          echo "Attempt $i..."
          
          # Request to API
          RESPONSE=$(curl -s -X POST "http://localhost:8000/predict" \
            -H "Content-Type: application/json" \
            -d '{"summary": "Nice", "text": "Really good quality", "HelpfulnessNumerator": 3, "HelpfulnessDenominator": 4}' || true)

          echo "Response: $RESPONSE"

          # Parse answer and der pred
          PREDICTION=$(echo "$RESPONSE" | jq -r '.prediction')

          # Check if gotten value is number
          if echo "$PREDICTION" | grep -Eq '^[0-9.]+$'; then
            echo "Inference successful: $PREDICTION"
            exit 0
          fi
        done

        # If API do not response correctly
        echo "API did not respond correctly after multiple attempts"
        echo "Showing logs from container:"
        docker logs review_api
        exit 1

    - name: Stop and remove container
      if: always()
      run: docker stop review_api && docker rm review_api
