name: Build, Test and Push Docker Image

on:
  pull_request:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r docker_requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest tests/

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/review_clf .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/review_clf

    - name: Trigger CD pipeline
      uses: peter-evans/workflow-dispatch@v1
      with:
        workflow: Deploy and Test Model Container
        token: ${{ secrets.GITHUB_TOKEN }}